sudo: false
language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
addons:
  firefox: latest-beta
notifications:
  irc: "irc.mozilla.org#jpm"
before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - npm install -g npm
install:
  - npm install
script:
  - export JPM_FIREFOX_BINARY=`which firefox`
  - npm run-script jshint
  - npm test
