sudo: false
language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
addons:
  firefox: latest-beta
notifications:
  irc: "irc.mozilla.org#jpm"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
install:
  - npm install
script:
  - export JPM_FIREFOX_BINARY=`which firefox`
  - npm run-script jshint
  - npm test
