sudo: false
language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"
env:
  - FIREFOX_VERSION=nightly
#  - FIREFOX_VERSION=aurora
#  - FIREFOX_VERSION=beta
#  - FIREFOX_VERSION=release

notifications:
  irc: "irc.mozilla.org#jpm"

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - npm install -g npm

install:
  - npm install

before_script:
  - pwd
  - cd ..
  - wget "https://download.mozilla.org/?product=firefox-nightly-latest&os=linux64&lang=en-US" -O firefox.tar.bz2 && tar xvf firefox.tar.bz2
  - cd $TRAVIS_BUILD_DIR
  - pwd

script:
  - export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
  - export JPM_BUILD_TYPE=travis
  - npm run-script jshint
  - npm test
